
let flags = [
    {imagem: "./assets/images/Bandeiras/australia.jpg",
     tag: "australia" },
    {imagem: "./assets/images/Bandeiras/austria.jpg" ,
    tag: "austria"},
    {imagem: "./assets/images/Bandeiras/belgica.jpg",
    tag: "belgica"},
    {imagem: "./assets/images/Bandeiras/bolivia.jpg",
    tag: "bolivia"},
    {imagem: "./assets/images/Bandeiras/coreia-do-sul.jpg" ,
    tag: "coreia do sul"},
    {imagem: "./assets/images/Bandeiras/egito.jpg",
    tag: "egito" },
    {imagem: "./assets/images/Bandeiras/equador.jpg",
    tag: "equador"},
    {imagem: "./assets/images/Bandeiras/eua.jpg",
    tag: "estados unidos"},
    {imagem: "./assets/images/Bandeiras/haiti.jpg",
    tag: "haiti" },
    {imagem: "./assets/images/Bandeiras/irlanda.jpg",
    tag: "irlanda"},
    {imagem: "./assets/images/Bandeiras/jamaica.jpg",
    tag: "jamaica"},
    {imagem: "./assets/images/Bandeiras/malasia.jpg",
    tag: "malasia"},
    {imagem: "./assets/images/Bandeiras/mexico.jpg",
    tag: "mexico"},
    {imagem: "./assets/images/Bandeiras/montenegro.jpg",
    tag: "montenegro"},
    {imagem: "./assets/images/Bandeiras/noruega.jpg",
    tag: "noruega"},
    {imagem: "./assets/images/Bandeiras/panama.jpg",
    tag: "panama"},
    {imagem: "./assets/images/Bandeiras/paquistão.jpg",
    tag: "paquistao"},
    {imagem: "./assets/images/Bandeiras/peru.jpg",
    tag: "peru"},
    {imagem: "./assets/images/Bandeiras/portugal.jpg",
    tag: "portugal"},
    {imagem: "./assets/images/Bandeiras/reino-unido.jpg",
    tag: "reino unido"},
    {imagem: "./assets/images/Bandeiras/senegal.jpg",
    tag: "senegal"},
    {imagem: "./assets/images/Bandeiras/servia.jpg",
    tag: "servia"},
    {imagem: "./assets/images/Bandeiras/singapura.jpg",
    tag: "singapura"},
    {imagem: "./assets/images/Bandeiras/somalia.jpg",
    tag: "somalia"},
    {imagem: "./assets/images/Bandeiras/suecia.jpg",
    tag: "suecia"},
    {imagem: "./assets/images/Bandeiras/tailandia.jpg",
    tag: "tailandia"},
    {imagem: "./assets/images/Bandeiras/tunisia.jpg",
    tag: "tunisia"},
    {imagem: "./assets/images/Bandeiras/turquia.jpg",
    tag: "turquia"},
    {imagem: "./assets/images/Bandeiras/vaticano.jpg",
    tag: "vaticano"},
    {imagem: "./assets/images/Bandeiras/vietna.jpg",
    tag: "vietna"}   
];

let movies = [
    {frame: "./assets/images/Filmes/2001-uma-odisseia-no-espaço.jpg",
    tag: "2001 uma odisseia no espaço"},
    {frame: "./assets/images/Filmes/a-vida-de-pi.jpg",
    tag: "a vida de pi"},
    {frame: "./assets/images/Filmes/o-show-de-truman.jpg",
    tag: "o show de truman"},
    {frame: "./assets/images/Filmes/blade-runner.jpg",
    tag: "blade runner"},
    {frame: "./assets/images/Filmes/cars.jpg",
    tag: "cars"},
    {frame: "./assets/images/Filmes/cidade-de-deus.jpg",
    tag: "cidade de deus"},
    {frame: "./assets/images/Filmes/clube-da-luta.jpg",
    tag: "clube da luta"},
    {frame: "./assets/images/Filmes/crepusculo.jpg",
    tag: "crepusculo"},
    {frame: "./assets/images/Filmes/de-volta-para-o-futuro.jpeg",
    tag: "de volta para o futuro"},
    {frame: "./assets/images/Filmes/forest-gump.jpg",
    tag: "forest gump"},
    {frame: "./assets/images/Filmes/interestelar.jpg",
    tag: "interestelar"},
    {frame: "./assets/images/Filmes/jurassicpark.jpg",
    tag: "jurassic park"},
    {frame: "./assets/images/Filmes/kill-bill.jpg",
    tag: "kill bill"},
    {frame: "./assets/images/Filmes/la-la-landa.jpg",
    tag: "la la land"},
    {frame: "./assets/images/Filmes/laranja-mecânica.jpg",
    tag: "laranja mecânica"},
    {frame: "./assets/images/Filmes/mad-max.jpg",
    tag: "mad max"},
    {frame: "./assets/images/Filmes/matrix.jpg",
    tag: "matrix"},
    {frame: "./assets/images/Filmes/na-natureza-selvagem.jpg",
    tag: "na natureza selvagem"},
    {frame: "./assets/images/Filmes/o-auto-da-compadecida.png",
    tag: "o auto da compadecida"},
    {frame: "./assets/images/Filmes/o-poderoso-chefão.jpg",
    tag: "o poderoso chefão"},
    {frame: "./assets/images/Filmes/os-vingadores.jpg",
    tag: "os vingadores"},
    {frame: "./assets/images/Filmes/pulp-fiction.jpeg",
    tag: "pulp fiction"},
    {frame: "./assets/images/Filmes/rocky.jpg",
    tag: "rocky"},
    {frame: "./assets/images/Filmes/senhor-dos-aneis.jpg",
    tag: "senhor dos aneis"},
    {frame: "./assets/images/Filmes/sociedade-dos-poetas-mortos.jpg" ,
    tag: "sociedade dos poetas mortos"},
    {frame: "./assets/images/Filmes/starwars.jpg",
     tag: "starwars"},
    {frame: "./assets/images/Filmes/hum-lugar-silencioso.jpg",
    tag: "um lugar silencioso"},
    {frame: "./assets/images/Filmes/hum-sonho-de-liberade.jpg",
    tag: "um sonho de liberade"},
    {frame: "./assets/images/Filmes/v-de-vingança.jpg",
    tag: "v de vingança"},
    {frame: "./assets/images/Filmes/velozes-e-furiosos.jpg",
    tag: "velozes e furiosos"}
    

]