
let flags = [
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\australia.jpg",
     tag: "australia" },
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\austria.jpg" ,
    tag: "austria"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\belgica.jpg",
    tag: "belgica"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\bolivia.jpg",
    tag: "bolivia"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\coreia-do-sul.jpg" ,
    tag: "coreia do sul"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\egito.jpg",
    tag: "egito" },
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\equador.jpg",
    tag: "equador"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\eua.jpg",
    tag: "estados unidos"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\haiti.jpg",
    tag: "haiti" },
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\irlanda.jpg",
    tag: "irlanda"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\jamaica.jpg",
    tag: "jamaica"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\malasia.jpg",
    tag: "malasia"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\mexico.jpg",
    tag: "mexico"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\montenegro.jpg",
    tag: "montenegro"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\noruega.jpg",
    tag: "noruega"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\panama.jpg",
    tag: "panama"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\paquistão.jpg",
    tag: "paquistão"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\peru.jpg",
    tag: "peru"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\portugal.jpg",
    tag: "portugal"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\reino-unido.jpg",
    tag: "reino unido"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\senegal.jpg",
    tag: "senegal"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\servia.jpg",
    tag: "servia"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\singapura.jpg",
    tag: "singapura"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\somalia.jpg",
    tag: "somalia"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\suecia.jpg",
    tag: "suecia"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\tailandia.jpg",
    tag: "tailandia"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\tunisia.jpg",
    tag: "tunisia"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\turquia.jpg",
    tag: "turquia"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\vaticano.jpg",
    tag: "vaticano"},
    {imagem: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Bandeiras\vietna.jpg",
    tag: "vietna"}   
];

let movies = [
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\2001-uma-odisseia-no-espaço.jpg",
    tag: "2001 uma odisseia no espaço"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\a-vida-de-pi.jpg",
    tag: "a vida de pi"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\o-show-de-truman.jpg",
    tag: "o show de truman"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\blade-runner.jpg",
    tag: "blade runner"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\cars.jpg",
    tag: "cars"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\cidade-de-deus.jpg",
    tag: "cidade de deus"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\clube-da-luta.jpg",
    tag: "clube da luta"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\crepusculo.jpg",
    tag: "crepusculo"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\de-volta-para-o-futuro.jpeg",
    tag: "de volta para o futuro"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\forest-gump.jpg",
    tag: "forest gump"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\interestelar.jpg",
    tag: "interestelar"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\jurassicpark.jpg",
    tag: "jurassic park"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\kill-bill.jpg",
    tag: "kill bill"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\la-la-landa.jpg",
    tag: "la la land"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\laranja-mecânica.jpg",
    tag: "laranja mecânica"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\mad-max.jpg",
    tag: "mad max"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\matrix.jpg",
    tag: "matrix"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\na-natureza-selvagem.jpg",
    tag: "na natureza selvagem"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\o-auto-da-compadecida.png",
    tag: "o auto da compadecida"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\o-poderoso-chefão.jpg",
    tag: "o poderoso chefão"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\os-vingadores.jpg",
    tag: "os vingadores"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\pulp-fiction.jpeg",
    tag: "pulp fiction"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\rocky.jpg",
    tag: "rocky"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\senhor-dos-aneis.jpg",
    tag: "senhor dos aneis"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\sociedade-dos-poetas-mortos.jpg" ,
    tag: "sociedade dos poetas mortos"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\starwars.jpg",
     tag: "starwars"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\um-lugar-silencioso.jpg",
    tag: "um lugar silencioso"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\um-sonho-de-liberade.jpg",
    tag: "um sonho de liberade"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\v-de-vingança.jpg",
    tag: "v de vingança"},
    {frame: "C:\Users\lucas\OneDrive\Área de Trabalho\Ironhack\71 WD FT\Projeto1\assets\images\Filmes\velozes-e-furiosos.jpg",
    tag: "velozes e furiosos"}
    

]